### ISSUE TITLE
fastify-auth sample seems not to work correctly

### ISSUE THREAD

**Issue by NJ69** [fastify/fastify-bearer-auth#80]
## 🐛 Bug Report

Using the delivered example for fastify-auth integration gives me an error: 
```js
(node:19472) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'bind' of undefined
    at Object.auth (E:\Files\Projects\Node.JS\Test\BetaLoad\masterapi\node_modules\fastify-auth\auth.js:33:33)
    at main (E:\Files\Projects\Node.JS\Test\BetaLoad\masterapi\main.js:17:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:19472) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:19472) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## To Reproduce

I used the example code as a base. Registering fastify-auth first with fastify. Then fastify-bearer-auth. I had to do this with await otherwise i got an error that app.auth() is not known.

Full code:
```js
'use strict'

const app = require('fastify')({
    logger: true
});
const bearerAuthPlugin = require('fastify-bearer-auth');
const fastifyAuth = require('fastify-auth');
const keys = new Set(['a-super-secret-key', 'another-super-secret-key']);

async function main() {
    await app.register(fastifyAuth);
    await app.register(bearerAuthPlugin, { addHook: false, keys});

    app.route({
        method: 'GET',
        url: '/multiauth',
        preHandler: app.auth([
            app.allowAnonymous,
            app.verifyBearerAuth
        ]),
        handler: function (_, reply) {
            reply.send({ hello: 'world' })
        }
    });

    app.listen({port: 3000}, (err, address) => {
        if (err) {
            app.log.error(err.message)
            process.exit(1)
        }
        app.log.info(`server listening on ${address}`);
    });
}

main();
```

## Expected behavior

Code should run.

## Your Environment

- *node version*: 12
- *fastify version*: 3.14.2
- *os*: Windows
- *fastify-auth version*: 1.1.0

**Comment by mcollina** [comment]
There is a problem in the example, `allowAnynonymous` is not defined anywhere. Look at:

https://github.com/fastify/fastify-bearer-auth/blob/2e7bcc4892614011d1f0335a75f939c638171322/test/integration.test.js#L61-L66

on how to define it.

Would you like to send a Pull Request to address this issue?

**Comment by NJ69** [comment]
thanks I will try that

**Comment by Fdawgs** [comment]
@NJ69 did you manage to solve this?
I appear to be running into the same issue, even without `allowAnonymous`.

**Comment by NJ69** [comment]
@Fdawgs sadly not
